version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: banking-service
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=bank
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    restart: unless-stopped
    command: ["-host=0.0.0.0", "-port=8080"]
    networks:
      - banking-network

  postgres:
    image: postgres:15-alpine
    container_name: banking-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bank
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - banking-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  banking-network:
    driver: bridge

volumes:
  postgres-data:
    driver: local
